### ISSUE TITLE
Security >>Audit Trail.. Error when opening audit trail component

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Kumulsoft-Fixed-Assets#11]
Refer attached error
![image](https://cloud.githubusercontent.com/assets/10192106/8926985/968a74b0-3557-11e5-8245-b9ab8dac9fff.png)

**Comment by agilecube** [comment]
Please ignore. AUDIT trail is not part of sprint 1.

**Comment by agilecube** [comment]
Please close

**Comment by mnarewec** [comment]
Not part of Sprint One.
